<h1> Atualizar Conta Bancária </h1>
<form action="/conta-bancaria/edit" method="post" id="formNovoArtigos"   >


                    <div class="form-group">
                        <label class="col-sm-2 control-label">Tipo Conta<span class="asterisco">*</span></label>
                        <div class="col-sm-9">

                  <select  name= "tipo_conta" id="tipo_conta">
                       <option value="1" selected="selected"> <?php echo $this->view->dados ['tipo_conta'] ?></option>
                          <option value="1" selected=""> Conta Corrente</option>
                          <option value="2" selected=""> Poupança</option>


                   </select>
                        </div>
                    </div>

                     <label class="col-sm-2 control-label">Banco<span class="asterisco">*</span></label>
                        <div class="col-sm-9">

                  <select  name= "banco" id="banco">
                        <option value="1" selected="selected"> <?php echo $this->view->dados ['banco'] ?></option>
                          <option value="3" selected="selected">Banco do Brasil</option>
                          <option value="4" selected="selected"> Bradesco</option>
                           <option value="5" selected="selected">Caixa</option>
                          <option value="6" selected="selected"> Itaú</option>


                   </select>
                        </div>
                    </div>


                        <label class="col-sm-2 control-label">Agência<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                             <input type="text" name="agencia" value="<?php echo $this->view->dados ['agencia'] ?>">
                        </div>

                        <label class="col-sm-2 control-label">Conta<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                             <input type="text" name="conta" value="<?php echo $this->view->dados ['conta'] ?>">
                        </div>

                        <label class="col-sm-2 control-label">Titular<span class="asterisco">*</span></label>
                        <div class="col-sm-9">
                             <input type="text" name="titular" value="<?php echo $this->view->dados ['titular'] ?>">
                        </div>

                      <label class="col-sm-2 control-label">Status<span class="asterisco">*</span></label>
                        <div class="col-sm-9">

                  <select  name= "status" id="status">
                        <option value="1" selected=""> <?php echo $this->view->dados ['status'] ?></option>
                          <option value="7" selected="selected">Ativo</option>
                          <option value="8" selected="selected"> Inativo</option>


                   </select>
                        </div>
                    </div>




</div>
</div>



                      <div class="form-group">
                        <div class="col-sm-12" style="padding-right:25px; margin-top: 20px;">
                            <button type="submit" class="btn btn-principal">Confirmar</button>


                        </div>

                        </div>
                    </div>
                </div>
            </form>